import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

// Do not move this file into src. Typescript resolution will not work in packages.
// tsconfig.json is generated by build script from tsconfig.json5, so it is not included in the repository.
export const config = JSON.parse(readFileSync(resolve(import.meta.dirname, './tsconfig.json'), 'utf8'))
export default config
